#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	counter cnt_accepted {
		comment "accepted packets"
	}
	counter cnt_dropped {
		comment "dropped packets"
	}
	chain input {
		type filter hook input priority filter; policy accept;
	}
	# purpose: block downstream devices from being reached directly from the internet
	# allow outbound new and outbound/inbound established
	# allow all traffic through wlan0 since that's for local devices on home network
	# block all inbound new traffic via default policy
	# default drop handles everything else
	chain forward {
		type filter hook forward priority filter; policy drop;
		ct state established,related counter name cnt_accepted accept;
		iifname "wlan0" oifname "eth0" ct state new counter name cnt_accepted accept;
		counter name cnt_dropped drop;
	}
	chain output {
		type filter hook output priority filter; policy accept;
	}
}

table inet nat {
	chain postrouting {
		type nat hook postrouting priority 100; policy accept;
		oifname "eth0" masquerade
	}
}
